name: simantan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.4
  sp_util: ^2.0.3
  image_picker: 0.8.6
  lazy_load_scrollview: 1.3.0
  expandable_text: 2.3.0
  chips_choice: 3.0.0
  like_button: 2.0.5
  image_downloader: ^0.31.0
  loading_animation_widget: ^1.2.0+3
  google_fonts: 3.0.1
  images_picker: ^1.2.11
  dio: 4.0.6
  external_path: ^1.0.3
  permission_handler: 10.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/logo-brand.png
    - assets/placeholder_image.jpg
  uses-material-design: true

